spring.application.name=Mobiles
spring.datasource.url=jdbc:mysql://localhost:3306/mobile_store
spring.datasource.username=root
spring.datasource.password=Janisha37

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
